version: '3.8'

services:
  # 1. FastAPI 应用
  app:
    build: .
    container_name: brand-monitor-app
    restart: always
    # 使用 host 网络模式，容器直接使用宿主机的网络栈
    # 这样 app 可以直接访问宿主机的 localhost:5432
    network_mode: host
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./static:/app/static
    env_file:
      - .env
    environment:
      # 强制使用 localhost，因为在 host 模式下，localhost 就是宿主机
      - POSTGRES_SERVER=localhost
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  # 2. Nginx 反向代理
  # Nginx 也需要使用 host 模式才能方便地代理到 localhost:8000
  nginx:
    image: nginx:alpine
    container_name: brand-monitor-nginx
    restart: always
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/app/static:ro